name: RubyCritic Check

on:
  push:
    branches:
      - '*'

jobs:
  rubycritic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: gem install rubycritic

    - name: Run RubyCritic
      run: rubycritic --format console
