name: Run Tests and Check Coverage

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up SimpleCov
      run: gem install simplecov

    - name: Run RSpec
      run: |
        bundle exec rails cucumber
        bundle exec rspec
      

  check-coverage:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install SimpleCov
      run: gem install simplecov

    - name: Check coverage
      run: |
        COVERAGE_THRESHOLD=90
        coverage=$COVERAGE
        echo "Code coverage is $coverage%."
        if (( $(echo "$coverage >= $COVERAGE_THRESHOLD" | bc -l) )); then
          echo "Code coverage is over 90%."
        else
          echo "Code coverage is below 90%."
          exit 1
        fi
